export const AccountBalance = [
  'Savings',
  'Checking',
  'Investment',
  'Credit Card',
  'Loan Account',
  'Mortgage',
  'Retirement',
  'Health Savings',
  'Education Savings',
  'Vacation Fund',
  'Emergency Fund',
  'Wedding Fund',
  'House Renovation',
  'Car Purchase',
  'Pet Savings',
  'Gadget Fund',
  'Travel Fund',
  'Christmas Fund',
  'Birthday Fund',
  'Anniversary Fund',
  'Business Account',
  'Personal Account',
  'Joint Account',
  'Trust Fund',
  'Charity Fund',
  'Tax Savings',
  'Child Savings',
  'College Fund',
  'Fixed Deposit',
  'Recurring Deposit',
  'Foreign Currency',
  'Precious Metals',
  'Real Estate',
  'Art Collection',
  'Private Equity',
  'Cryptocurrency',
  'Commodities',
  'Treasury Bonds',
  'Municipal Bonds',
  'Corporate Bonds',
  'High Yield Savings',
  'Money Market',
  'Certificate of Deposit',
  'Roth IRA',
  'Traditional IRA',
  '401(k)',
  'SEP IRA',
  'Simple IRA',
  'Brokerage Account',
  'Rollover IRA',
];
